/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTodosGetCollection200ResponseHydraSearchHydraMappingInner } from './apiTodosGetCollection200ResponseHydraSearchHydraMappingInner';


export interface ApiTodosGetCollection200ResponseHydraSearch { 
    type?: string;
    hydratemplate?: string;
    hydravariableRepresentation?: string;
    hydramapping?: Array<ApiTodosGetCollection200ResponseHydraSearchHydraMappingInner>;
}

