/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoJsonldContext } from './todoJsonldContext';


/**
 * 
 */
export interface TodoJsonld {
    context?: TodoJsonldContext;
    // readonly id?: string;
    readonly type?: string;
    readonly id?: number;
    name?: string;
    description?: string;
}

