/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiTodosGetCollection200Response } from '../model/models';
import { Todo } from '../model/models';
import { TodoJsonld } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiTodosGetCollectionRequestParams {
    page?: number;
}

export interface ApiTodosIdDeleteRequestParams {
    id: string;
}

export interface ApiTodosIdGetRequestParams {
    id: string;
}

export interface ApiTodosIdPatchRequestParams {
    id: string;
    todo: Todo;
}

export interface ApiTodosIdPutRequestParams {
    id: string;
    todoJsonld: TodoJsonld;
}

export interface ApiTodosPostRequestParams {
    todoJsonld: TodoJsonld;
}


export interface TodoServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Retrieves the collection of Todo resources.
     * Retrieves the collection of Todo resources.
* @param requestParameters
     */
    apiTodosGetCollection(requestParameters: ApiTodosGetCollectionRequestParams, extraHttpRequestParams?: any): Observable<ApiTodosGetCollection200Response>;

    /**
     * Removes the Todo resource.
     * Removes the Todo resource.
* @param requestParameters
     */
    apiTodosIdDelete(requestParameters: ApiTodosIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Retrieves a Todo resource.
     * Retrieves a Todo resource.
* @param requestParameters
     */
    apiTodosIdGet(requestParameters: ApiTodosIdGetRequestParams, extraHttpRequestParams?: any): Observable<TodoJsonld>;

    /**
     * Updates the Todo resource.
     * Updates the Todo resource.
* @param requestParameters
     */
    apiTodosIdPatch(requestParameters: ApiTodosIdPatchRequestParams, extraHttpRequestParams?: any): Observable<TodoJsonld>;

    /**
     * Replaces the Todo resource.
     * Replaces the Todo resource.
* @param requestParameters
     */
    apiTodosIdPut(requestParameters: ApiTodosIdPutRequestParams, extraHttpRequestParams?: any): Observable<TodoJsonld>;

    /**
     * Creates a Todo resource.
     * Creates a Todo resource.
* @param requestParameters
     */
    apiTodosPost(requestParameters: ApiTodosPostRequestParams, extraHttpRequestParams?: any): Observable<TodoJsonld>;

}
